---
- name: Install rbenv and dependence packages
  homebrew: name={{ item }} update_homebrew=yes
  with_items: rbenv_packages

- name: Install ruby
  shell: rbenv versions | grep {{ item }} || rbenv install {{ item }}
  register: result
  changed_when: '"Downloading " in result.stdout'
  with_items: ruby_versions

- name: Install gems for all ruby versions
  shell: rbenv global {{ item[0] }} && rbenv exec gem list --local | grep {{ item[1] }} || rbenv exec gem install {{ item[1] }}
  register: result
  changed_when: '"Successfully installed " in result.stdout'
  with_nested:
    - ruby_versions
    - gem_essential_packages

- name: Configure ruby's global version
  shell: rbenv global | grep {{ ruby_version }} || rbenv global {{ ruby_version }}
  register: result
  changed_when: '"{{ ruby_version }}" not in result.stdout'

- name: Install gems
  gem: name={{ item }} state=latest user_install=no executable={{ gem_path }}
  with_items: gem_packages
