---

git_config:
  user:
    name: trkw
    email: trkw@trkw.me
  color:
    branch: auto
    diff: auto
    interactive: auto
    status: auto
    ui: auto
  core:
    editor: "'vim -c \"set fenc=utf-8\"'"
    precomposeunicode: true
    quotepath: false
  diff:
    tool: vimdiff
  push:
    default: simple
