---
- name: Install homesick
  gem: name=homesick state=latest user_install=no executable={{ gem_path }}

- name: Clone dotfiles
  command: rbenv exec homesick clone {{ homesick_repository }}
  register: result
  changed_when: '" exist " not in result.stdout'

- name: Pull dotfiles
  command: rbenv exec homesick pull

- name: Link dotfiles
  command: rbenv exec homesick link --force
  register: result
  changed_when: '" symlink " in result.stdout'
